name: pybnafar
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - pyarrow
  - numpy
  - requests
  - beautifulsoup4
  - tqdm
  - streamlit
  - plotly
  - pip
  - pip:
      - fhir.resources>=7.1.0
      - .
